[package]
name = "auf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.22", features = ["derive"] }
trust-dns-client = "0.23.0"
whois-rust = "1.5.1"
